[package]
name = "hg-examples"
readme = "../README.md"
version.workspace = true
edition.workspace = true
license .workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
hg = { path = "../hg" }
thiserror = "2.0.12"
